export const ADD_NUMBER = "ADD_NUMBER"
export const SUB_NUMBER = "SUB_NUMBER"

export const GET_BANNERS = "GET_BANNERS"
export const GET_RECOMMENDS = "GET_RECOMMENDS"

export const GET_HOMEDATA = "GET_HOMEDATA"

export const FETCH_HOMEDATA = "FETCH_HOMEDATA"
